export const BILL_DELETE='BILL_DELETE';
export const BILL_DELETE_REQUEST='BILL_DELETE_REQUEST';
export const BILL_DELETE_SUCCESS='BILL_DELETE_SUCCESS';
export const BILL_DELETE_ERROR='BILL_DELETE_ERROR';
export const BILL_DELETE_Reset='BILL_DELETE_Reset';