export const GET_COUNT_VIEW_PRODUCT='GET_COUNT_VIEW_PRODUCT';

export const INSERT_COUNT_VIEW_PRODUCT='INSERT_COUNT_VIEW_PRODUCT';

export const UPDATE_COUNT_VIEW_PRODUCT='UPDATE_COUNT_VIEW_PRODUCT';

export const INSERT_SUCCESS_COUNT_VIEW_PRODUCT='INSERT_SUCCESS_COUNT_VIEW_PRODUCT';

export const INSERT_ERROR_COUNT_VIEW_PRODUCT='INSERT_ERROR_COUNT_VIEW_PRODUCT';

export const UPDATE_SUCCESS_COUNT_VIEW_PRODUCT='UPDATE_SUCCESS_COUNT_VIEW_PRODUCT';

export const UPDATE_ERROR_COUNT_VIEW_PRODUCT='UPDATE_ERROR_COUNT_VIEW_PRODUCT';